[[manager.prepend_keymap]]
on  = "k"
run = "plugin arrow -1"

[[manager.prepend_keymap]]
on  = "j"
run = "plugin arrow 1"

[[input.prepend_keymap]]
on   = "<Esc>"
run  = "close"
desc = "Cancel input"

[[manager.prepend_keymap]]
on   = "l"
run  = "plugin smart-enter"
desc = "Enter the child directory, or open the file"

[[manager.prepend_keymap]]
on = "<C-p>"
run = 'shell -- qlmanage -p "$@"'
desc = "MacOS: Preview files with the system Quick Look"
