import = ["~/.config/alacritty/themes/themes/palenight.toml"]

[shell]
program = "/bin/zsh"
args = ["-l", "-c", "tmux attach -t main || tmux new -s main"]

[font]
normal.family = "JetBrainsMono Nerd Font"
bold.family = "JetBrainsMono Nerd Font"
italic.family = "JetBrainsMono Nerd Font"
offset.y = 10
glyph_offset.y = 5
size = 16.0

[window]
decorations = "Buttonless"
dimensions.columns = 125
dimensions.lines = 30
opacity = 0.8
blur = true
